//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3D.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S3D.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1}.
        /// </summary>
        internal static string AboutDialog_ApplicationName {
            get {
                return ResourceManager.GetString("AboutDialog_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutDialog_Caption {
            get {
                return ResourceManager.GetString("AboutDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string AboutDialog_Contact {
            get {
                return ResourceManager.GetString("AboutDialog_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2007-2009 skwas. All rights reserved. Use at your own risk. Distribution, commercial use and or (re)selling of this program are prohibited. Developed in 2007-2009 by skwas, a game enthusiast and ubergeek  :o).
        /// </summary>
        internal static string AboutDialog_Copyright {
            get {
                return ResourceManager.GetString("AboutDialog_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer:.
        /// </summary>
        internal static string AboutDialog_DisclaimerHeader {
            get {
                return ResourceManager.GetString("AboutDialog_DisclaimerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubi, SH dev team, SubSim.com. Also, individuals: tater, Anvart, Bando, WEBSTER, maikarant, Jace11, WilhelmTell, lurbz, Sansal, longam, PepsiCan, UBOAT234, Digital_Trucker, DirtyHarry3033, Kaleun_Endrass, sergbuto, SquareSteelBar, sober, jaketoox, reallydedpoet, swdw, nautilus42, nvdrifter, kapitan_zur_see, DeepIron, panthercules, l3th4l, Laffertytig, alamwuhk2a, privateer, g_BonE, Ducimus, lurker_hlb3, haegemon, wildchild, urfisch, LukeFF, ref, kikn79, WernerSobe, Redwine, GuillermoZS, keltos01, Mikhayl, Kr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutDialog_MoreThanks {
            get {
                return ResourceManager.GetString("AboutDialog_MoreThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More thanks to (feedback, suggestions, or for just being kind :)):.
        /// </summary>
        internal static string AboutDialog_MoreThanksHeader {
            get {
                return ResourceManager.GetString("AboutDialog_MoreThanksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptainCox (logo/artwork), DivingDuck (file structure, 3D), LeoVampire (08-01-2008, R.I.P.).
        /// </summary>
        internal static string AboutDialog_SpecialThanks {
            get {
                return ResourceManager.GetString("AboutDialog_SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks (in random order):.
        /// </summary>
        internal static string AboutDialog_SpecialThanksHeader {
            get {
                return ResourceManager.GetString("AboutDialog_SpecialThanksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is NOT endorsed or sponsered by Ubisoft Entertainment, publisher of the Silent Hunter® franchise..
        /// </summary>
        internal static string AboutDialog_UbiDisclaimer {
            get {
                return ResourceManager.GetString("AboutDialog_UbiDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent Hunter®: Wolves of the Pacific is a registered trademark of Ubisoft Entertainment..
        /// </summary>
        internal static string AboutDialog_UbiTM {
            get {
                return ResourceManager.GetString("AboutDialog_UbiTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutHeader {
            get {
                object obj = ResourceManager.GetObject("AboutHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new material.
        /// </summary>
        internal static string AddMaterialDialog_Caption {
            get {
                return ResourceManager.GetString("AddMaterialDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add a material with id 0..
        /// </summary>
        internal static string AddMaterialDialog_InvalidValueException {
            get {
                return ResourceManager.GetString("AddMaterialDialog_InvalidValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify material id:.
        /// </summary>
        internal static string AddMaterialDialog_SpecifyMaterial {
            get {
                return ResourceManager.GetString("AddMaterialDialog_SpecifyMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlphaBackground {
            get {
                object obj = ResourceManager.GetObject("AlphaBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All game files (*.dat; *.sim; *.zon; *.val; *.cam; *.dsd; *.anm; *.prt; *.fx; *.chr)
        ///*.dat; *.sim; *.zon; *.val; *.cam; *.dsd; *.anm; *.prt; *.fx; *.chr
        ///DAT files (*.dat)
        ///*.dat
        ///SIM files (*.sim)
        ///*.sim
        ///Sensor files (*.zon)
        ///*.zon
        ///VAL files (*.val)
        ///*.val
        ///Camera files (*.cam)
        ///*.cam
        ///DSD files (*.dsd)
        ///*.dsd
        ///Animation files - SH3 (*.anm)
        ///*.anm
        ///PRT files (*.prt)
        ///*.prt
        ///FX files (*.fx)
        ///*.fx
        ///CHR files (*.chr)
        ///*.chr
        ///All files (*.*)
        ///*.*.
        /// </summary>
        internal static string DatEditorFileFilters {
            get {
                return ResourceManager.GetString("DatEditorFileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All game files (*.dat; *.sim; *.zon; *.val; *.cam; *.dsd; *.anm; *.prt; *.fx; *.chr; *.sdl; *.off)
        ///*.dat; *.sim; *.zon; *.val; *.cam; *.dsd; *.anm; *.prt; *.fx; *.chr; *.sdl; *.off
        ///DAT files (*.dat)
        ///*.dat
        ///SIM files (*.sim)
        ///*.sim
        ///Sensor files (*.zon)
        ///*.zon
        ///VAL files (*.val)
        ///*.val
        ///Camera files (*.cam)
        ///*.cam
        ///DSD files (*.dsd)
        ///*.dsd
        ///Animation files - SH3 (*.anm)
        ///*.anm
        ///PRT files (*.prt)
        ///*.prt
        ///FX files (*.fx)
        ///*.fx
        ///CHR files (*.chr)
        ///*.chr
        ///Sound libraries (*.sdl)
        ///*.sdl
        ///Bitmap font character  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditorFileFilters {
            get {
                return ResourceManager.GetString("EditorFileFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to open the file in Explorer.
        ///
        ///{0}.
        /// </summary>
        internal static string Error_OpenFileInExplorer {
            get {
                return ResourceManager.GetString("Error_OpenFileInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export raw chunk.
        /// </summary>
        internal static string ExportChunkDialog_Caption {
            get {
                return ResourceManager.GetString("ExportChunkDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: When reimporting a chunk without a header, be sure to &apos;replace&apos; chunk data, instead of inserting a new chunk. Otherwise this tool and/or the game may interpret the data incorrectly and crash. Unless you know what you are doing, always include the header to be safe..
        /// </summary>
        internal static string ExportChunkDialog_ExportWarning {
            get {
                return ResourceManager.GetString("ExportChunkDialog_ExportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include chunk header (12 bytes=type, sub type, chunk size)..
        /// </summary>
        internal static string ExportChunkDialog_IncludeChunkHeader {
            get {
                return ResourceManager.GetString("ExportChunkDialog_IncludeChunkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        internal static string ExportChunkDialog_SettingsHeader {
            get {
                return ResourceManager.GetString("ExportChunkDialog_SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dds.
        /// </summary>
        internal static string File_Extension_DDS {
            get {
                return ResourceManager.GetString("File_Extension_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        internal static string File_Extension_PNG {
            get {
                return ResourceManager.GetString("File_Extension_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tga.
        /// </summary>
        internal static string File_Extension_TGA {
            get {
                return ResourceManager.GetString("File_Extension_TGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDraw surface files (*.dds)|*.dds.
        /// </summary>
        internal static string FileFilter_DDS {
            get {
                return ResourceManager.GetString("FileFilter_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported image formats (*.dds; *.tga)|*.dds;*.tga.
        /// </summary>
        internal static string FileFilter_ImageFormats {
            get {
                return ResourceManager.GetString("FileFilter_ImageFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics (*.png)|*.png.
        /// </summary>
        internal static string FileFilter_PNG {
            get {
                return ResourceManager.GetString("FileFilter_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targa files (*.tga)|*.tga.
        /// </summary>
        internal static string FileFilter_TGA {
            get {
                return ResourceManager.GetString("FileFilter_TGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Properties.
        /// </summary>
        internal static string FileInfoDialog_Caption {
            get {
                return ResourceManager.GetString("FileInfoDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string FileInfoDialog_Dates {
            get {
                return ResourceManager.GetString("FileInfoDialog_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains renderable objects (0x10000).
        /// </summary>
        internal static string FileInfoDialog_DatHeader_0x10000 {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatHeader_0x10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown (0x1000000). Seems to be related to graphs..
        /// </summary>
        internal static string FileInfoDialog_DatHeader_0x1000000 {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatHeader_0x1000000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic, always set (0x2). Should always be checked..
        /// </summary>
        internal static string FileInfoDialog_DatHeader_0x2 {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatHeader_0x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To my knowledge the flags above are not required to be correct by the SH-engine, but my guess is they affect the order the game loads each file. I have not fully investigated this but it makes sense to have some basic toplevel flag to tell the engine which files to load first or at what point certain content must be loaded.
        ///
        ///A dat-header looks like this:
        /// • File magic (uint) = always 0x716d0da4
        /// • File flags (uint) = the combined value above
        /// • Reserved0 (uint) = always 0
        ///Total 12 bytes..
        /// </summary>
        internal static string FileInfoDialog_DatHeader_Remarks {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatHeader_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined value:.
        /// </summary>
        internal static string FileInfoDialog_DatHeader_Value {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatHeader_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat-header.
        /// </summary>
        internal static string FileInfoDialog_DatHeaderGroup {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatHeaderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat-info.
        /// </summary>
        internal static string FileInfoDialog_DatInfo {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. of chunks.
        /// </summary>
        internal static string FileInfoDialog_DatInfo_NrOfChunks {
            get {
                return ResourceManager.GetString("FileInfoDialog_DatInfo_NrOfChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp; location.
        /// </summary>
        internal static string FileInfoDialog_NameAndLocation {
            get {
                return ResourceManager.GetString("FileInfoDialog_NameAndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not saved..
        /// </summary>
        internal static string FileInfoDialog_NotSaved {
            get {
                return ResourceManager.GetString("FileInfoDialog_NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related files.
        /// </summary>
        internal static string FileInfoDialog_RelatedFiles {
            get {
                return ResourceManager.GetString("FileInfoDialog_RelatedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdl-info.
        /// </summary>
        internal static string FileInfoDialog_SdlInfo {
            get {
                return ResourceManager.GetString("FileInfoDialog_SdlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. of sound entries.
        /// </summary>
        internal static string FileInfoDialog_SdlInfo_NrOfEntries {
            get {
                return ResourceManager.GetString("FileInfoDialog_SdlInfo_NrOfEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View file information..
        /// </summary>
        internal static string FileInformation_MinimizedToolTip {
            get {
                return ResourceManager.GetString("FileInformation_MinimizedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search files for id.
        /// </summary>
        internal static string FileSearchDialog_Caption {
            get {
                return ResourceManager.GetString("FileSearchDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched {0} files in: {1}.
        /// </summary>
        internal static string FileSearchDialog_Completed {
            get {
                return ResourceManager.GetString("FileSearchDialog_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File types:.
        /// </summary>
        internal static string FileSearchDialog_FilterFileTypes {
            get {
                return ResourceManager.GetString("FileSearchDialog_FilterFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        internal static string FileSearchDialog_IncludeSubFolders {
            get {
                return ResourceManager.GetString("FileSearchDialog_IncludeSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string FileSearchDialog_Initializing {
            get {
                return ResourceManager.GetString("FileSearchDialog_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options:.
        /// </summary>
        internal static string FileSearchDialog_OptionsGroup {
            get {
                return ResourceManager.GetString("FileSearchDialog_OptionsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching: {0}.
        /// </summary>
        internal static string FileSearchDialog_Progress {
            get {
                return ResourceManager.GetString("FileSearchDialog_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to search:.
        /// </summary>
        internal static string FileSearchDialog_RootFolder {
            get {
                return ResourceManager.GetString("FileSearchDialog_RootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled....
        /// </summary>
        internal static string FileSearchDialog_SearchCancelled {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for id:.
        /// </summary>
        internal static string FileSearchDialog_SearchForId {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id&apos;s: {0}, parent id&apos;s: {1}, model ref id&apos;s: {2}.
        /// </summary>
        internal static string FileSearchDialog_SearchHit {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string FileSearchDialog_SearchIn {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All id fields.
        /// </summary>
        internal static string FileSearchDialog_SearchIn_All {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchIn_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id field.
        /// </summary>
        internal static string FileSearchDialog_SearchIn_Id {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchIn_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model reference id field.
        /// </summary>
        internal static string FileSearchDialog_SearchIn_ModelId {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchIn_ModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent id field.
        /// </summary>
        internal static string FileSearchDialog_SearchIn_ParentId {
            get {
                return ResourceManager.GetString("FileSearchDialog_SearchIn_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons16x16_32bbp {
            get {
                object obj = ResourceManager.GetObject("Icons16x16_32bbp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InvalidBitmap {
            get {
                object obj = ResourceManager.GetObject("InvalidBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leovampire {
            get {
                object obj = ResourceManager.GetObject("leovampire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockConstraintsHorizontal {
            get {
                object obj = ResourceManager.GetObject("LockConstraintsHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgBox_Error {
            get {
                return ResourceManager.GetString("MsgBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MsgBox_Information {
            get {
                return ResourceManager.GetString("MsgBox_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string MsgBox_InvalidInputTitle {
            get {
                return ResourceManager.GetString("MsgBox_InvalidInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MsgBox_Question {
            get {
                return ResourceManager.GetString("MsgBox_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MsgBox_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PayPal {
            get {
                object obj = ResourceManager.GetObject("PayPal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PictureBoxEx {
            get {
                object obj = ResourceManager.GetObject("PictureBoxEx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SegoeUI {
            get {
                object obj = ResourceManager.GetObject("SegoeUI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Str_Advanced {
            get {
                return ResourceManager.GetString("Str_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Str_Author {
            get {
                return ResourceManager.GetString("Str_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Str_Description {
            get {
                return ResourceManager.GetString("Str_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Str_Details {
            get {
                return ResourceManager.GetString("Str_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open.
        /// </summary>
        internal static string Str_DoubleClickToOpen {
            get {
                return ResourceManager.GetString("Str_DoubleClickToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Str_FileCreationTime {
            get {
                return ResourceManager.GetString("Str_FileCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessed.
        /// </summary>
        internal static string Str_FileLastAccessTime {
            get {
                return ResourceManager.GetString("Str_FileLastAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Str_FileLastWriteTime {
            get {
                return ResourceManager.GetString("Str_FileLastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Str_FileLocation {
            get {
                return ResourceManager.GetString("Str_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Str_FileName {
            get {
                return ResourceManager.GetString("Str_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Str_FileSize {
            get {
                return ResourceManager.GetString("Str_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Str_Folder {
            get {
                return ResourceManager.GetString("Str_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Str_Found {
            get {
                return ResourceManager.GetString("Str_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Str_General {
            get {
                return ResourceManager.GetString("Str_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Str_NA {
            get {
                return ResourceManager.GetString("Str_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Str_Name {
            get {
                return ResourceManager.GetString("Str_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Str_No {
            get {
                return ResourceManager.GetString("Str_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Str_Property {
            get {
                return ResourceManager.GetString("Str_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3D signature.
        /// </summary>
        internal static string Str_S3DSignature {
            get {
                return ResourceManager.GetString("Str_S3DSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bytes.
        /// </summary>
        internal static string Str_SizeInBytes {
            get {
                return ResourceManager.GetString("Str_SizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        internal static string Str_SizeInGB {
            get {
                return ResourceManager.GetString("Str_SizeInGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        internal static string Str_SizeInKB {
            get {
                return ResourceManager.GetString("Str_SizeInKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        internal static string Str_SizeInMB {
            get {
                return ResourceManager.GetString("Str_SizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Str_Unknown {
            get {
                return ResourceManager.GetString("Str_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Str_Value {
            get {
                return ResourceManager.GetString("Str_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Str_Yes {
            get {
                return ResourceManager.GetString("Str_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnlockConstraintsHorizontal {
            get {
                object obj = ResourceManager.GetObject("UnlockConstraintsHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string not allowed. Specify {0} or choose cancel to reset to the original value..
        /// </summary>
        internal static string ValidatingInput_EmptyString {
            get {
                return ResourceManager.GetString("ValidatingInput_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Some extended render attributes and the texture file name (if specified) can not be saved, when &apos;explicit texture&apos; is disabled. While the file remains open in S3D, this data can be reverted when this change is undone, but as soon as the file is closed this information is lost..
        /// </summary>
        internal static string Warning_Save_Implicit_Texture {
            get {
                return ResourceManager.GetString("Warning_Save_Implicit_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search is currently in progress. Do you want to abort the search?.
        /// </summary>
        internal static string Warning_SearchInProgress {
            get {
                return ResourceManager.GetString("Warning_SearchInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=skwas%40skwas%2enet&amp;item_name=Support%20S3D%20%28donation%29&amp;no_shipping=0&amp;no_note=1&amp;tax=0&amp;currency_code=EUR&amp;lc=US&amp;bn=PP%2dDonationsBF&amp;charset=UTF%2d8.
        /// </summary>
        internal static string WebAddress_PayPal {
            get {
                return ResourceManager.GetString("WebAddress_PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object similar to System.Windows.Forms.AxHost+State.
        /// </summary>
        internal static object wmpState {
            get {
                object obj = ResourceManager.GetObject("wmpState", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap xmas {
            get {
                object obj = ResourceManager.GetObject("xmas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
